export const randomPrompts = [
    "A forest at sunset",
    "A futuristic cityscape",
    "A dragon breathing fire",
    "An underwater scene with colorful fish",
    "A majestic mountain range",
    "A group of hot air balloons flying in the sky",
    "A tropical island paradise",
    "A spooky abandoned mansion",
    "A busy city street at night",
    "A field of sunflowers",
    "A carnival with rides and games",
    "A desert oasis",
    "A medieval castle with a moat",
    "A futuristic space station",
    "A garden in full bloom",
    "A snowy landscape with a cozy cabin",
    "A winding river through a canyon",
    "A bustling farmer's market",
    "A tranquil lake at dawn",
    "A train station with steam trains",
    "A circus with clowns and acrobats",
    "A winter wonderland with snowmen and sleds",
    "A pirate ship on the open sea",
    "A vineyard in the countryside",
    "A bustling airport terminal",
    "A haunted cemetery at night",
    "A futuristic hovercraft in the city",
    "A cozy coffee shop on a rainy day",
    "A magical fairy garden",
    "A spooky forest with mist and fog",
    "A traditional Japanese tea garden",
    "A small village in the mountains",
    "A futuristic city with flying cars",
    "A peaceful meadow with wildflowers",
    "A space shuttle launching into orbit",
    "A coastal town with a lighthouse",
    "A night sky with stars and constellations",
    "A deserted island with palm trees",
    "A futuristic robot factory",
    "A whimsical candy land",
    "A wild west town with cowboys and horses",
    "A bustling casino in Las Vegas",
    "A science laboratory with test tubes and equipment",
    "A modern skyscraper city",
    "A tranquil beach at sunset",
    "A creepy abandoned asylum",
    "A steampunk city with airships",
    "A fairy tale castle with a drawbridge",
    "A snowy forest with wolves and owls",
    "A busy subway station during rush hour"
  ];
  