// The homepage of the application

import { useState,useEffect } from "react"
import { Loader, Card, Forms } from "../components"

const Home = () => {

  const [loading,setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)

    return (
      <section className="max-1-7x1 mx-auto">
        <div>
          <h1 className="font-extrabold text-[#22238] text-[32px]">Showcase Room</h1>
          <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">Take a look at a compilation of visually breathtaking pictures generated by PixelWit</p>
        </div>
      </section>
    )
  }
  
  export default Home